stages:
  load_data:
    cmd: python src/component/data_ingestion.py --config=params.yaml
    deps:
    - src/utility.py
    - https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
    outs:
    - artifacts/data/wine_quality.csv
    - artifacts/data/train.csv
    - artifacts/data/test.csv
    - artifacts/data/val.csv


  training:
    cmd: python src/pipeline/training.py --config=params.yaml
    deps:
      - artifacts/data/train.csv
      - artifacts/data/test.csv
      - src/utility.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    outs:
      - artifacts/model/wime_model.pkl